TaskSaasAPP/urls.py
from django.urls import re_path, include
from django.contrib import admin

# app_name = 'TaskSaas'

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    # path('chat/', include('chat.urls')),
    re_path(r'^TaskSaas/', include(('TaskSaas.urls', 'TaskSaas'), namespace='TaskSaas')),
    re_path(r'^TaskChat/', include(('TaskChat.urls', 'TaskChat'), namespace='TaskChat')),
    re_path(r'^', include('web.urls')),
]

web/urls.py
from django.conf.urls import static
from django.urls import re_path, include, path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from TaskChat import chat_views, consumers
from TaskSaas.api import oauth_callback_api, user_api, collect_api, wx_api, calendar, project_user_api, reply_api
from web.views import account, home, project, manage, issues, cache, setting, file, wiki, dashboard, tool, module, \
    sentry, userinfo_view, glory, milestone, sys_config
from web.views.upload import FileUploadView

urlpatterns = [
    # scheduler.run(),

    re_path(r'^MP_verify_O7ZsD2KZoE5w9Usg.txt/', wx_api.wx_verify_txt, name='wx_verify_txt'),
    re_path(r'^wechat_entry_api/', wx_api.wx_entry_api, name='wechat_entry_api'),
    re_path(r'^wechat_callback_api/', wx_api.wx_callback_api, name='wechat_callback_api'),

    path('token_login', TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path('token_refresh', TokenRefreshView.as_view(), name="token_refresh"),
    path('token_verify', TokenVerifyView.as_view(), name="token_verify"),

    re_path(r'^static/(?P<path>.*)$', static.serve, {'document_root': 'web/static'}, name='static'),
    re_path(r'^register/', account.register, name='register'),
    re_path(r'^login/sms/', account.login_sms, name='login_sms'),
    re_path(r'^login/', account.login, name='login'),
    re_path(r'^login/', account.login, name='login'),

    re_path(r'^do_login/', account.do_login, name='do_login'),
    re_path(r'^do_profile/', userinfo_view.do_profile, name='do_profile'),
    re_path(r'^get_token/', account.get_token, name='get_token'),
    re_path(r'^get_user_by_openid/', userinfo_view.get_user_by_openid, name='get_user_by_openid'),
    re_path(r'^bind_user_with_openid/', userinfo_view.bind_user_with_openid, name='bind_user_with_openid'),



    re_path(r'^logout/', account.logout, name='logout'),
    re_path(r'^image/code/', account.image_code, name='image_code'),
    re_path(r'^send/sms/', account.send_sms, name='send_sms'),
    re_path(r'^index/', home.index, name='index'),
    re_path(r'^help/', home.help, name='help'),
    re_path(r'^/', home.index, name=''),
    re_path(r'^callback/gitlab/$', oauth_callback_api.callback, name='callback'),
    # re_path(r'^callback/gitlab/token/', oauth_callback_api.callback_token, name='callback_token'),
    re_path(r'^gitlab/myprofile/$', oauth_callback_api.callback_userpassword, name='git_myprofile'),
    re_path(r'^webhook/gitlab/$', oauth_callback_api.webhook_callback, name='webhook_callback'),
    path('', home.index, name=''),

    re_path(r'^upload/(?P<filename>[^/]+)$', FileUploadView.as_view()),
    # re_path(r'^issues_status_cache_set/', cache.issues_status_cache_set, name='issues_status_cache'),
    # 项目列表
    re_path(r'^project/list/', project.project_list, name='project_list'),
    # 项目列表json response
    re_path(r'^project_list/', project.project_list_json, name='project_list_json'),
    re_path(r'^do_issue_list/', issues.do_issue_list, name='do_issue_list'),

    re_path(r'^glory_list/', glory.GloryAPI.as_view(), name='glory_list'),
    re_path(r'^glory_detail/(?P<glory_id>\d+)', glory.glory_detail, name='glory_detail'),
    # dashboard json response
    re_path(r'^dashboard_json/$', dashboard.dashboard_json, name='dashboard_json'),

    re_path(r'^project/star/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_star, name='project_star'),
    re_path(r'^project/unstar/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_unstar,
            name='project_unstar'),

    re_path(r'^workbench_json/$', manage.workbench_json, name='workbench_json'),
    re_path(r'^remind_json/$', manage.remind_json, name='remind_json'),
    # 项目管理
    # 路由分发
    re_path(r'^sys_config/$', setting.sys_config, name='sys_config'),
    re_path(r'^sys_config_notify/$', sys_config.sys_config_notify, name='sys_config_notify'),
    re_path(r'^sys_config_template/$', sys_config.sys_config_template, name='sys_config_template'),
    re_path(r'^sys_config_notify_switch/$', sys_config.sys_config_notify_switch, name='sys_config_notify_switch'),

    re_path(r'^profile/$', user_api.profile, name='profile'),
    re_path(r'^profile_git/$', user_api.profile_git, name='profile_git'),

    re_path(r'^sentry_evt/', sentry.sentry_evt, name='sentry_evt'),
    re_path(r'^sentry_setup/', sentry.sentry_setup, name='sentry_setup'),

    re_path(r'^fileupload/$', file.uploadfile_common, name='fileupload'),
    re_path(r'^profileupload/$', file.uploadfile_profile, name='profileupload'),


re_path(r'^manage/(?P<project_id>\d+)/', include([

    re_path(r'^cache_set/', cache.cache_set, name='cache'),
    re_path(r'^day_cache_set/', cache.day_cache_set, name='day_cache'),
    re_path(r'^main_echart_legend_cache_set/', cache.main_echart_legend_cache_set, name='main_echart_legend_cache'),
    re_path(r'^echart_legend_cache_set/', cache.echart_legend_cache_set, name='echart_legend_cache'),
    re_path(r'^attention_cache_set/', cache.attention_cache_set, name='attention_cache'),

    re_path(r'^statistics/$', manage.statistics, name='statistics'),
    re_path(r'^milestone/$', milestone.milestone, name='milestone'),
    re_path(r'^milestone_add_or_update/$', milestone.milestone_add_or_update, name='milestone_add_or_update'),
    re_path(r'^milestone_del/$', milestone.milestone_del, name='milestone_del'),
    re_path(r'^git/$', manage.git, name='git'),
    re_path(r'^tool/$', manage.tool, name='tool'),
    re_path(r'^tool_generate_str/$', tool.generate_random_chinese_string, name='tool_generate_str'),
    re_path(r'^tool_encrypt_druid_password/$', tool.encrypt_druid_password, name='tool_encrypt_druid_password'),
    re_path(r'^resolve_mask_of_ipv4/$', tool.resolve_mask_of_ipv4, name='resolve_mask_of_ipv4'),
    # re_path(r'^color_picker/$', tool.color_picker, name='color_picker'),

    re_path(r'^workbench/$', manage.workbench, name='workbench'),
    re_path(r'^calendar/$', manage.calendar, name='calendar'),
    re_path(r'^remind/$', manage.remind, name='remind'),

    # 导出工作内容
    re_path(r'^calendar_time_range_export_works/$', calendar.calendar_time_range_export_works, name='calendar_time_range_export_works'),
    # 导出任务列表
    re_path(r'^calendar_time_range_export_tasks/$', calendar.calendar_time_range_export_tasks, name='calendar_time_range_export_tasks'),

    re_path(r'^remind_status/$', manage.remind_status, name='remind_status'),
    re_path(r'^remind_readed_all/$', manage.remind_readed_all, name='remind_readed_all'),
    re_path(r'^collect/$', manage.collect, name='collect'),
    re_path(r'^make_collect/$', collect_api.make_collect, name='make_collect'),
    re_path(r'^wiki_collect/$', collect_api.wiki_collect, name='wiki_collect'),
    re_path(r'^file_collect/$', collect_api.file_collect, name='file_collect'),

    re_path(r'^wiki/$', wiki.wiki, name='wiki'),
    re_path(r'^wiki/add/$', wiki.wiki_add, name='wiki_add'),
    re_path(r'^wiki/delete/(?P<wiki_id>\d+)/$', wiki.wiki_delete, name='wiki_delete'),
    re_path(r'^wiki/edit/(?P<wiki_id>\d+)/$', wiki.wiki_edit, name='wiki_edit'),
    re_path(r'^wiki/upload/', wiki.wiki_upload, name='wiki_upload'),
    re_path(r'^wiki/catalog/', wiki.wiki_catalog, name='wiki_catalog'),

    re_path(r'^file/$', file.file, name='file'),
    re_path(r'^file/delete/$', file.file_delete, name='file_delete'),
    re_path(r'^cos/credential/$', file.cos_credential, name='cos_credential'),
    re_path(r'^file/post/$', file.upload_file, name='file_post'),
    re_path(r'^file/download/(?P<file_id>\d+)/$', file.file_download, name='file_download'),

    re_path(r'^setting/$', setting.setting, name='setting'),
    re_path(r'^setting/delete/$', setting.setting_delete, name='setting_delete'),
    re_path(r'^setting/common/$', setting.setting_common, name='setting_common'),
    re_path(r'^setting/common_spider/$', setting.setting_common_spider, name='setting_common_spider'),
    re_path(r'^setting/module/$', module.setting_module, name='setting_module'),
    re_path(r'^setting/module_del/$', module.setting_module_del, name='setting_module_del'),

    re_path(r'^issues/$', issues.issues, name='issues'),
    re_path(r'^issues/detail/(?P<issues_id>\d+)/$', issues.issues_detail, name='issues_detail'),
    re_path(r'^issues/record/(?P<issues_pk>\d+)/$', issues.issues_record, name='issues_record'),
    re_path(r'^issues/change/(?P<issues_pk>\d+)/$', issues.issues_change, name='issues_change'),
    re_path(r'^issues/del/$', issues.issues_del, name='issues_del'),
    re_path(r'^issues/invite/url/$', issues.invite_url, name='invite_url'),

    #delete reply by id
    re_path(r'^del_reply/$', reply_api.del_reply, name='del_reply'),

    re_path(r'^dashboard/$', dashboard.dashboard, name='dashboard'),

    re_path(r'^send_private_hint_msg/$', consumers.send_private_hint_msg, name='send_private_hint_msg'),
    re_path(r'^received_userlist_status/$', consumers.received_userlist_status, name='received_userlist_status'),

    # work_record
    re_path(r'^add_work_record/$', manage.work_record, name='add_work_record'),
    re_path(r'^work_record_update/$',  manage.work_record_update, name='work_record_update'),
    re_path(r'^find_work_record/$',  manage.find_work_record, name='find_work_record'),
    re_path(r'^work_record_list/$',  manage.work_record_list, name='work_record_list'),


    #remove user from project by invitee
    re_path(r'^remove_user_from_project/$',  project_user_api.remove_user_from_project, name='remove_user_from_project'),








], None)),

# re_path(r'^chat/', include([
#     path('', chat_views.chat, name='chat-url'),
#     # path('<str:room_name>/', chat_views.room, name='room'),
#     path('ws/', consumers.ChatConsumer.as_asgi()),
# ], None)),

    # re_path('tool/',include([
    #     path('', manage.tool, name='tool'),
    #     re_path(r'^generate/(?P<str_length>\d+)/$', tool.generate_random_chinese_string,name='tool_generate_str'),
    # ],None)),

    # 邀请页面

web/forms/account.py
# Create your views here.
import random

from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from django_redis import get_redis_connection

from utils.tencent.sms import send_sms_single

from web import models
from django.core.validators import RegexValidator
from utils import encrypt
from web.forms.bootstrap import BootStrapForm


class RegisterModelForm(BootStrapForm, forms.ModelForm):
    """
    注册表单自动生成
    """
    password = forms.CharField(label='密码', min_length=6, max_length=18, error_messages={
        'min_length': '密码长度不能小于6个字符',
        'max_length': '密码长度不能大于18个字符'
    }, widget=forms.PasswordInput())

    confirm_password = forms.CharField(label='重复密码', min_length=6, max_length=18, error_messages={
        'min_length': '重复密码长度不能小于6个字符',
        'max_length': '重复密码长度不能大于18个字符'
    }, widget=forms.PasswordInput())
    # mobile_phone = forms.CharField(label='手机号码',
    #                                validators=[RegexValidator(r'^(1[3|4|5|6|7|8|9])\d{9}$', '手机号码格式错误'), ])

    # code = forms.CharField(label='验证码', widget=forms.TextInput())

    class Meta:
        model = models.UserInfo
        fields = ['username', 'email', 'password', 'confirm_password' ]

    def clean_username(self):
        username = self.cleaned_data['username']
        exists = models.UserInfo.objects.filter(username=username).exists()
        if exists:
            raise ValidationError('用户名已存在')
        return username

    def clean_wechat_openid(self):
        wechat_openid = self.cleaned_data['wechat_openid']
        return wechat_openid

    def clean_email(self):
        email = self.cleaned_data['email']
        exists = models.UserInfo.objects.filter(email=email).exists()
        if exists:
            raise ValidationError('邮箱已存在')
        return email

    def clean_password(self):
        password = self.cleaned_data["password"]
        # 加密 & 返回
        return encrypt.md5(password)

    def clean_confirm_password(self):
        password = self.cleaned_data['password']
        confirm_password = encrypt.md5(self.cleaned_data['confirm_password'])
        if password != confirm_password:
            raise ValidationError("两次密码不一致！")
        return confirm_password

    # def clean_mobile_phone(self):
    #     mobile_phone = self.cleaned_data['mobile_phone']
    #     exists = models.UserInfo.objects.filter(mobile_phone=mobile_phone).exists()
    #     if exists:
    #         raise ValidationError('手机号已注册')
    #     return mobile_phone

    # def clean_code(self):
    #     code = self.cleaned_data['code']
    #     mobile_phone = self.cleaned_data.get('mobile_phone')
    #     if not mobile_phone:
    #         return code
    #
    #     conn = get_redis_connection()
    #     redis_code = conn.get(mobile_phone)
    #     if not redis_code:
    #         raise ValidationError('验证码已过期！')
    #
    #     redis_str_code = redis_code.decode('utf-8')
    #
    #     if code.strip() != redis_str_code:
    #         raise ValidationError('验证码错误！')
    #     return code


class SendSmsForm(forms.Form):
    """
    发送短信
    """
    mobile_phone = forms.CharField(label='手机号码',
                                   validators=[RegexValidator(r'^(1[3|4|5|6|7|8|9])\d{9}$', '手机号码格式错误'), ])

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    def clean_mobile_phone(self):
        """手机号码校验的钩子"""
        mobile_phone = self.cleaned_data['mobile_phone']
        # 判断短信模板是否有问题
        tpl = self.request.GET.get('tpl')
        template_id = settings.TENCENT_SMS_TEMPLATES.get(tpl)
        if not template_id:
            raise ValidationError('短信模板错误')

        exists = models.UserInfo.objects.filter(mobile_phone=mobile_phone).exists()

        code = random.randrange(1000, 9999)
        # 校验数据库中是否有该号码
        # 发短信 & 写redis
        if tpl == 'login':
            if not exists:
                raise ValidationError('手机号码不存在')
            sms = send_sms_single(mobile_phone, template_id, [code, 1])
        else:
            if exists:
                raise ValidationError('手机号码已存在')
            sms = send_sms_single(mobile_phone, template_id, [code, ])

        if sms['result'] != 0:
            raise ValidationError('短信发送失败, {}'.format(sms['errmsg']))

        # 验证码写入redis(使用django-redis)
        conn = get_redis_connection("default")
        conn.set(mobile_phone, code, ex=60)

        return mobile_phone


class LoginSmsForm(BootStrapForm, forms.Form):
    """
    短信登陆表单生成
    """
    mobile_phone = forms.CharField(label='手机号码',
                                   validators=[RegexValidator(r'^(1[3|4|5|6|7|8|9])\d{9}$', '手机号码格式错误'), ])

    # code = forms.CharField(label='验证码', widget=forms.TextInput())

    # def clean_mobile_phone(self):
    #     mobile_phone = self.cleaned_data['mobile_phone']
    #     user_object = models.UserInfo.objects.filter(mobile_phone=mobile_phone).first()
    #     if not user_object:
    #         raise ValidationError('手机号码不存在')
    #     return user_object

    # def clean_code(self):
    #     code = self.cleaned_data['code']
    #     user_object = self.cleaned_data.get('mobile_phone')
    #     # 手机号不存在，验证码无需校验
    #     if not user_object:
    #         return code
    #
    #     conn = get_redis_connection()
    #     redis_code = conn.get(user_object.mobile_phone)
    #
    #     if not redis_code:
    #         raise ValidationError('验证码失效，请重新发送！')
    #
    #     redis_str_code = redis_code.decode('utf-8')
    #
    #     if code.strip() != redis_str_code:
    #         raise ValidationError('验证码错误，请重新输入！')
    #
    #     return code


class LoginForm(BootStrapForm, forms.Form):
    """
    密码登陆表单生成
    """
    username = forms.CharField(label='邮箱或用户名')
    password = forms.CharField(label='密码', widget=forms.PasswordInput())
    # code = forms.CharField(label='图片验证码')

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    def clean_password(self):
        password = self.cleaned_data['password']
        return encrypt.md5(password)

    # def clean_code(self):
    #     """
    #     校验图片验证码
    #     :return:
    #     """
    #     code = self.cleaned_data['code']
    #     session_code = self.request.session.get('image_code')
    #     if not session_code:
    #         raise ValidationError("验证码已过期，请重试！")
    #
    #     if code.strip().upper() != session_code.upper():
    #         raise ValidationError('验证码错误，请重试！')
    #
    #     return code

web/views/sys_config.py
from django.http import JsonResponse
from django.shortcuts import render


def sys_config_notify(request):
    return render(request, 'web/sys_config_notify.html')
def sys_config_template(request):
    return render(request, 'web/sys_config_template.html')

def sys_config_notify_switch(request):
    return JsonResponse({'status':1})

web/templates/web/collect.html
{% extends 'layout/manage.html' %}
{% load dashboard %}
{% load issues %}
{% block title %}{% endblock %}

{% block css %}
    <style>

        .switch {
            position: relative;
            display: inline-block;
            width: 60px;
            height: 34px;
        }

        .switch input {
            opacity: 0;
            width: 0;
            height: 17px;
        }

        .slider {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #ccc;
            -webkit-transition: .4s;
            transition: .4s;
        }

        .slider:before {
            position: absolute;
            content: "";
            height: 26px;
            width: 26px;
            left: 4px;
            bottom: 4px;
            background-color: white;
            -webkit-transition: .4s;
            transition: .4s;
        }

        input:checked + .slider {
            background-color: #2196F3;
        }

        input:focus + .slider {
            box-shadow: 0 0 1px #2196F3;
        }

        input:checked + .slider:before {
            -webkit-transform: translateX(26px);
            -ms-transform: translateX(26px);
            transform: translateX(26px);
        }

        /* Rounded sliders */
        .slider.round {
            border-radius: 34px;
        }

        .slider.round:before {
            border-radius: 50%;
        }

        .table-right > tbody > tr > td.label-left {
            width: 90px;
        }

        .table-right > tbody > tr > td {
            border: 0;
        }

        .status-count {
            text-align: center;
            margin-top: 10px;
            margin-bottom: 30px;
            font-size: 14px;
        }

        .status-count .count {
            font-size: 25px;
        }

        .status-count a {
            text-decoration: none;
        }

        .user-item .title {
            margin-bottom: 20px;
        }

        .user-item .avatar, .top-10 .avatar {
            float: left;
            margin-right: 10px;
            display: inline-block;
            width: 30px;
            height: 30px;
            background-color: #304659;
            color: white;
            text-align: center;
            line-height: 30px;
            border-radius: 50%;
        }

        .user-item .text {
            line-height: 30px;
        }

        .top-10 .avatar {
            margin-right: 0;
        }

        .top-10 td {
            padding: 5px 10px;
        }

        .top-10 .table > tbody > tr > td {
            border-top: 0;
            border-bottom: 1px solid #ddd;
        }
    </style>

{% endblock %}

{% block content %}
    <div class="container-fluid" style="margin-top: 20px">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-history" aria-hidden="true"></i>
                        收藏 {{ coll_size }} 条

                    </div>
                    <div class="panel-body top-10">
                        <table class="table"
                               style="word-wrap:break-word;word-break:break-all;height:auto;min-height: 100vh;display: block;overflow-y: scroll;">
                            <tbody>
                            {#                            <span class="label label-default"> Label</span>#}
                            {#                            <span class="label label-default label-success"> Label</span>#}
                            {#                            <span class="label label-default label-danger"> Label</span>#}
                            {#                            <span class="label label-default label-primary"> Label</span>#}
                            {% for key,item in collects.items %}


                                {#                                                                {{ key }}#}
                                {#                                {{ item }}#}
                                <tr>

                                    <td class="col-md-4">
                                            <label class="label label-default label-primary"
                                                   for="">project: <label>{{ item.project }}</label></label>


                                        {% if item.avatar %}
                                            {#                                            <img class="avatar" src="{{ item.avatar }}" alt="">#}
                                        {% else %}
                                            {#                                            <div class="avatar">{{ item.creator.0|upper }}</div>#}
                                        {% endif %}
                                    </td>
                                <td class="col-md-2">
                                     <label class="label label-default label-primary"
                                                   for="">type: <label>{{ item.type }}</label></label>

                                </td>
                                    <td class="col-md-6">
                                        <label
                                                style="color: green">
                                            <a href="{{ item.link }}"
                                               style="color:dodgerblue;text-decoration: underline dotted"
                                               target="_blank">{{ item.title }}</a>
                                        </label>
                                    </td>

                                </tr>

                            {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <input id="csrf_token" value="{{ csrf_token }}" hidden="hidden"/>
{% endblock %}

{% block js %}
    <script type="text/javascript">

    </script>
{% endblock %}

web/templates/web/index.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %} 首页 {% endblock %}

{% block css %}
    <style>
        img {
            width: 100%;
        }
    </style>
{% endblock %}

{% block content %}

    <div class="container-fluid">
        {#    <div class="col-md-12 panel-info"#}
        {#         style="text-align: center">#}

        <div style="width: 380px;" class="center-block">
            <button type="button" onclick="goDashboard()" class="center-block layui-btn layui-btn-fluid">管理中心
            </button>
        </div>

        {#        <canvas style="padding-top: 20px"></canvas>#}
        <img src="{% static 'web/image/image-1.png' %}">
        <img src="{% static 'web/image/image-2.png' %}">
        <img src="{% static 'web/image/image-3.png' %}">
        <img src="{% static 'web/image/image-4.png' %}">
        {#    </div>#}
    </div>
{% endblock %}

{% block js %}

    <script>
        function goDashboard() {
            window.location.href = "{% url 'project_list' %}";
        }

        {% comment %}let canvas = document.querySelector('canvas');
        let ctx = canvas.getContext('2d');
        canvas.width = window.innerWidth * 1;
        canvas.height = window.innerHeight * 0.85;
        let str = "makemestronger".split('');
        let arr = Array(Math.ceil(canvas.width / 10)).fill(0);
        let run = () => {
            ctx.fillStyle = 'rgba(0,0,0,0.05)';
            ctx.fillRect(0, 0, canvas.width, canvas.height);
            ctx.fillStyle = '#0f0';
            arr.forEach((item, index) => {
                ctx.fillText(str[Math.floor(Math.random() * str.length)], index * 10, item + 10);
                arr[index] = item > canvas.height || item > 10000 * Math.random() ? 0 : item + 10;
            });
        };
        // run()
        setInterval(run, 40);{% endcomment %}


        layui.use(['layer'], function (args) {
            var layer = layui.layer;
            layer.msg('TaskSaas')
        });

    </script>

{% endblock %}

web/templates/web/invite_join.html
{% extends 'layout/manage.html' %}

{% block title %}加入项目{% endblock %}

{% block css %}
    <style>
        .no-radius {
            border-radius: 0;
            text-align: center;
        }
    </style>
{% endblock %}

{% block content %}
    <div>
        {% if error %}
            <div class="alert alert-danger no-radius">
                <h4><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> {{ error }}</h4>
            </div>
        {% else %}
            <div class="alert alert-success no-radius">
                <h4><i class="fa fa-check-circle" aria-hidden="true"></i> 加入成功 </h4>
                <a href="{% url 'dashboard' project_id=project.id %}">点击跳转至项目</a>
            </div>
        {% endif %}

    </div>

{% endblock %}

web/templates/web/register.html
{% extends "layout/basic.html" %}
{% load static %}

{% block title %} 用户注册 {% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'web/css/account.css' %}">
    <style>
        .error-msg {
            color: red;
            position: absolute;
            font-size: 13px;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="account">
        <h1 style="text-align: center">用户注册</h1>
        <form id="regForm" method="POST" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="clearfix">
                            <div class="col-md-6" style="padding-left: 0px">{{ field }}
                                <span class="error-msg"></span>
                            </div>
                            <div class="col-md-6"><input id="btnSms" type="button" class="btn btn-default"
                                                         value="点击获取验证码"></div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg"></span>
                    </div>
                {% endif %}
            {% endfor %}
            <input id="btnSubmit" type="button" class="btn btn-primary" value="注  册">
        </form>
    </div>
{% endblock %}


{% block js %}
    <script>
        //页面框架加载完成自动执行
        $(function () {
            bindClickBtnSms();
            bindClickBtnSubmit();
        });

        /*
        * 点击注册提交
        * */
        function bindClickBtnSubmit() {
            $('#btnSubmit').click(function () {
                $('.error-msg').empty();
                //收集表单数据 $('#regForm').serialize()
                //获取所有字段数据+csrf_token
                //数据ajax传到后台
                $.ajax({
                    url: "{% url 'register' %}",
                    type: "POST",
                    data: $('#regForm').serialize(),
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            location.href = res.data;
                        } else {
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }


        /*
        * 点击获取验证码的按钮绑定事件
        * */
        function bindClickBtnSms() {
            $('#btnSms').click(function () {
                $(".error-msg").empty();

                //获取用户手机号
                //找到手机号输入框的ID，根据ID获取值
                var mobile_Phone = $('#id_mobile_phone').val();


                //发送ajax请求，把手机号发送过去
                $.ajax({
                    url: "{% url 'send_sms' %}",
                    type: "GET",
                    data: {
                        mobile_phone: mobile_Phone,
                        tpl: "register"
                    },
                    dataType: "JSON",
                    success: function (res) {
                        //ajax请求发送成功之后，自动执行的函数
                        if (res.status) {
                            sendSmsRemind();
                        } else {
                            //{status:False,error:{mobile_phone:['错误信息',]}}
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }

        /*
        * 请求成功，计时器开始
        * */
        function sendSmsRemind() {
            var $smsBtn = $('#btnSms');
            $smsBtn.prop('disabled', true);//禁用

            var time = 59;
            var remind = setInterval(function () {
                $smsBtn.val(time + '秒重新发送');
                time = time - 1;
                if (time < 1) {
                    clearInterval();
                    $smsBtn.val('点击获取验证码').prop('disabled', false);
                }
            }, 1000);
        }

    </script>
{% endblock %}